docs(fs): add css button integration
france-connect/Documentation-AgentConnect pull request #12
Opened 2023-11-22 14:52 UTC by douglasduteil

<p align="center">
    <img src="https://media.giphy.com/media/ZVlFjKDrDolqy3L9om/giphy.gif">
</p>

2023-11-22 17:39 UTC, rdubigny requested changes
Hello ! merci pour cet update. 

On va partir sur un design copié collé du bouton FC avec uniquement un changement de label. Est ce que tu peux ajuster la background color en conséquence ?

Par ailleurs, est ce que tu peux ajouter un lien vers la doc react dsfr ?

2023-11-28 11:41 UTC, douglasduteil commented
> On va partir sur un design copié collé du bouton FC avec uniquement un changement de label. Est ce que tu peux ajuster la background color en conséquence ?

Concrètement :  

|Idle|Hover|
| --- | --- |
|![image](https://github.com/france-connect/Documentation-AgentConnect/assets/730511/b916572e-6903-42d8-a3d9-11fd3e170b22) |![image](https://github.com/france-connect/Documentation-AgentConnect/assets/730511/a40913e5-b375-4a75-b2b0-616c604a9a45)|

Devient 

|Idle|Hover|
| --- | --- |
|![image](https://github.com/france-connect/Documentation-AgentConnect/assets/730511/3a547ce6-eee9-4e5a-9fe8-cd0aef0bc385) | ![image](https://github.com/france-connect/Documentation-AgentConnect/assets/730511/b2e5e438-dbc7-4770-9540-f3fd6a52c6ba)|


 ?

2023-12-11 10:52 UTC, douglasduteil commented
[AFK discussion]

2023-12-11 10:53 UTC, douglasduteil commented
The answer is **yes**

2024-01-03 10:58 UTC, douglasduteil commented
🆙 @rdubigny

2024-01-12 10:25 UTC, rdubigny approved these changes

2024-01-12 10:25 UTC, merged