Add login hint and claims
france-connect/Documentation-AgentConnect pull request #35
Opened 2024-09-30 11:43 UTC by BenoitSerrano

2024-10-01 08:23 UTC, rdubigny commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQFS, sur la documentation, je sais quoi faire du paramètre claims](https://trello.com/c/YvrhHyXy/206-etqfs-sur-la-documentation-je-sais-quoi-faire-du-param%C3%A8tre-claims)

2024-10-01 10:01 UTC, rdubigny requested changes

2024-10-01 10:01 UTC, rdubigny commented on resources/claim_amr.md
> +| `prompt`     | `login` |
tu es sûr qu'il faille demander un `prompt=login` en plus ? 🤔

2024-10-01 10:01 UTC, rdubigny commented on resources/claim_amr.md
> +| mfa        | Authentification à deux facteurs.
important de laisser le lien vers la doc FC je pense.

2024-10-01 10:01 UTC, rdubigny commented on doc_fi/configuration.md
> +Si votre FI gère l'authentification multi-facteur, alors il vous faut renseigner dans le claim `amr` la valeur correspondant à ce mode d'authentification. Cela permettra aux Fournisseurs de Service d
En réalité, il faudrait retourner l'`amr` même pour une authentification simple facteur. Par exemple les valeurs `pwd` et `mail` peuvent correspondre à une authentification simple facteur.

2024-10-02 07:45 UTC, BenoitSerrano commented on resources/claim_amr.md
> +| `prompt`     | `login` |
J'ai copié la doc de MCP j'av ! Mais si tu me poses la question, ça veut dire qu'il faut que je droppe ça :D

2024-10-02 07:46 UTC, BenoitSerrano commented on resources/claim_amr.md
> +| mfa        | Authentification à deux facteurs.
Habile Bill

2024-10-02 07:46 UTC, BenoitSerrano commented on doc_fi/configuration.md
> +Si votre FI gère l'authentification multi-facteur, alors il vous faut renseigner dans le claim `amr` la valeur correspondant à ce mode d'authentification. Cela permettra aux Fournisseurs de Service d
Bien compris !

2024-10-02 15:14 UTC, rdubigny approved these changes

2024-10-02 15:14 UTC, merged